### ISSUE TITLE
Feature request: white background

### ISSUE THREAD

**Issue by mpartio** [andrew-MET/harpVis#1]
Black background does not work will with presentations / posters. Can we have an option for white background?

**Comment by andrew-MET** [comment]
This will be included in the forthcoming download handler with a preview (and choice of background colour, title, subtitle and caption). I will consider adding a button to toggle the background colour of the app as well, though the UI is already getting a bit cluttered with new features!

**Comment by andrew-MET** [comment]
Download handler added: https://github.com/andrew-MET/harpVis/commit/9a6a4dd6af30f48ad572751d85051f87b5c44f40
