### ISSUE TITLE
Do not change score in interactive mode when parameter is changed

### ISSUE THREAD

**Issue by mpartio** [andrew-MET/harpVis#2]
It would be nice in the "interactive" tab in the web interface if the chosen score were kept when a new parameter is loaded. At the moment it goes back to CRPS.

**Comment by andrew-MET** [comment]
Will look into this. It's maybe not as straightforward as it sounds, so the priority will be quite low for now.

**Comment by andrew-MET** [comment]
sorted: https://github.com/andrew-MET/harpVis/commit/9a6a4dd6af30f48ad572751d85051f87b5c44f40
