### ISSUE TITLE
Date is reset when parameter is changed

### ISSUE THREAD

**Issue by mpartio** [andrew-MET/harpVis#6]
The Shiny app "forgets" the user-selected verification date whenever parameter is changed. 

Can it be changed so that the date doesn't change?

**Steps to reproduce:**

Make sure you have at least two dates available in "Date" dropdown and also at least two parameters. Choose the latter date and first parameter. Then change the parameter.

**Expected result:**

The date selected would remain and only parameter is changed.

**Actual result:**

The date is "reset" to first date in the list.

**Version:**

```
> library(harpVis)
Loading required package: ggplot2
Loading required package: shiny
> print(packageVersion("harpVis"))
[1] ‘0.0.0.9048’
```

**Comment by andrew-MET** [comment]
Will try and fix it early next year

**Comment by andrew-MET** [comment]
fixed: https://github.com/andrew-MET/harpVis/commit/f5450e178230f4e00b22f803e58d0887ca15d776
