### ISSUE TITLE
Picks up wrong rds file

### ISSUE THREAD

**Issue by uandrae** [andrew-MET/harpVis#7]
With a mixture of files like 

...*harp.CMEPS_preop.model.MEPS_prod_shifted_6h.model.MEPS_prod.rds
...*harp.CMEPS_preop.rds

In my verification directory I can choose dates from the first case even if I pick "CMEPS_preop" only as the "Model combination" in the web interface. It seems like the file name recognition is not strict enough.

**Comment by andrew-MET** [comment]
will look at in 2020

**Comment by andrew-MET** [comment]
fixed: https://github.com/andrew-MET/harpVis/commit/f5450e178230f4e00b22f803e58d0887ca15d776
